# permissions for end users to view mickadeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mickadeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-test
    app.kubernetes.io/part-of: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: mickadeployment-viewer-role
rules:
- apiGroups:
  - webapp.micka.com
  resources:
  - mickadeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.micka.com
  resources:
  - mickadeployments/status
  verbs:
  - get
